# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/hcchen/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/hcchen/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hcchen/Desktop/BadmintonCourt/CourtDetect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hcchen/Desktop/BadmintonCourt/CourtDetect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/hcchen/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/hcchen/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hcchen/Desktop/BadmintonCourt/CourtDetect/CMakeFiles /home/hcchen/Desktop/BadmintonCourt/CourtDetect//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hcchen/Desktop/BadmintonCourt/CourtDetect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named detect

# Build rule for target.
detect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 detect
.PHONY : detect

# fast build rule for target.
detect/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/build
.PHONY : detect/fast

CourtLineCandidateDetector.o: CourtLineCandidateDetector.cpp.o
.PHONY : CourtLineCandidateDetector.o

# target to build an object file
CourtLineCandidateDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/CourtLineCandidateDetector.cpp.o
.PHONY : CourtLineCandidateDetector.cpp.o

CourtLineCandidateDetector.i: CourtLineCandidateDetector.cpp.i
.PHONY : CourtLineCandidateDetector.i

# target to preprocess a source file
CourtLineCandidateDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/CourtLineCandidateDetector.cpp.i
.PHONY : CourtLineCandidateDetector.cpp.i

CourtLineCandidateDetector.s: CourtLineCandidateDetector.cpp.s
.PHONY : CourtLineCandidateDetector.s

# target to generate assembly for a file
CourtLineCandidateDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/CourtLineCandidateDetector.cpp.s
.PHONY : CourtLineCandidateDetector.cpp.s

CourtLinePixelDetector.o: CourtLinePixelDetector.cpp.o
.PHONY : CourtLinePixelDetector.o

# target to build an object file
CourtLinePixelDetector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/CourtLinePixelDetector.cpp.o
.PHONY : CourtLinePixelDetector.cpp.o

CourtLinePixelDetector.i: CourtLinePixelDetector.cpp.i
.PHONY : CourtLinePixelDetector.i

# target to preprocess a source file
CourtLinePixelDetector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/CourtLinePixelDetector.cpp.i
.PHONY : CourtLinePixelDetector.cpp.i

CourtLinePixelDetector.s: CourtLinePixelDetector.cpp.s
.PHONY : CourtLinePixelDetector.s

# target to generate assembly for a file
CourtLinePixelDetector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/CourtLinePixelDetector.cpp.s
.PHONY : CourtLinePixelDetector.cpp.s

DebugHelpers.o: DebugHelpers.cpp.o
.PHONY : DebugHelpers.o

# target to build an object file
DebugHelpers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/DebugHelpers.cpp.o
.PHONY : DebugHelpers.cpp.o

DebugHelpers.i: DebugHelpers.cpp.i
.PHONY : DebugHelpers.i

# target to preprocess a source file
DebugHelpers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/DebugHelpers.cpp.i
.PHONY : DebugHelpers.cpp.i

DebugHelpers.s: DebugHelpers.cpp.s
.PHONY : DebugHelpers.s

# target to generate assembly for a file
DebugHelpers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/DebugHelpers.cpp.s
.PHONY : DebugHelpers.cpp.s

GlobalParameters.o: GlobalParameters.cpp.o
.PHONY : GlobalParameters.o

# target to build an object file
GlobalParameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/GlobalParameters.cpp.o
.PHONY : GlobalParameters.cpp.o

GlobalParameters.i: GlobalParameters.cpp.i
.PHONY : GlobalParameters.i

# target to preprocess a source file
GlobalParameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/GlobalParameters.cpp.i
.PHONY : GlobalParameters.cpp.i

GlobalParameters.s: GlobalParameters.cpp.s
.PHONY : GlobalParameters.s

# target to generate assembly for a file
GlobalParameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/GlobalParameters.cpp.s
.PHONY : GlobalParameters.cpp.s

LicenseChecker.o: LicenseChecker.cpp.o
.PHONY : LicenseChecker.o

# target to build an object file
LicenseChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/LicenseChecker.cpp.o
.PHONY : LicenseChecker.cpp.o

LicenseChecker.i: LicenseChecker.cpp.i
.PHONY : LicenseChecker.i

# target to preprocess a source file
LicenseChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/LicenseChecker.cpp.i
.PHONY : LicenseChecker.cpp.i

LicenseChecker.s: LicenseChecker.cpp.s
.PHONY : LicenseChecker.s

# target to generate assembly for a file
LicenseChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/LicenseChecker.cpp.s
.PHONY : LicenseChecker.cpp.s

Line.o: Line.cpp.o
.PHONY : Line.o

# target to build an object file
Line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/Line.cpp.o
.PHONY : Line.cpp.o

Line.i: Line.cpp.i
.PHONY : Line.i

# target to preprocess a source file
Line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/Line.cpp.i
.PHONY : Line.cpp.i

Line.s: Line.cpp.s
.PHONY : Line.s

# target to generate assembly for a file
Line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/Line.cpp.s
.PHONY : Line.cpp.s

TennisCourtFitter.o: TennisCourtFitter.cpp.o
.PHONY : TennisCourtFitter.o

# target to build an object file
TennisCourtFitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TennisCourtFitter.cpp.o
.PHONY : TennisCourtFitter.cpp.o

TennisCourtFitter.i: TennisCourtFitter.cpp.i
.PHONY : TennisCourtFitter.i

# target to preprocess a source file
TennisCourtFitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TennisCourtFitter.cpp.i
.PHONY : TennisCourtFitter.cpp.i

TennisCourtFitter.s: TennisCourtFitter.cpp.s
.PHONY : TennisCourtFitter.s

# target to generate assembly for a file
TennisCourtFitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TennisCourtFitter.cpp.s
.PHONY : TennisCourtFitter.cpp.s

TennisCourtModel.o: TennisCourtModel.cpp.o
.PHONY : TennisCourtModel.o

# target to build an object file
TennisCourtModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TennisCourtModel.cpp.o
.PHONY : TennisCourtModel.cpp.o

TennisCourtModel.i: TennisCourtModel.cpp.i
.PHONY : TennisCourtModel.i

# target to preprocess a source file
TennisCourtModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TennisCourtModel.cpp.i
.PHONY : TennisCourtModel.cpp.i

TennisCourtModel.s: TennisCourtModel.cpp.s
.PHONY : TennisCourtModel.s

# target to generate assembly for a file
TennisCourtModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TennisCourtModel.cpp.s
.PHONY : TennisCourtModel.cpp.s

TimeMeasurement.o: TimeMeasurement.cpp.o
.PHONY : TimeMeasurement.o

# target to build an object file
TimeMeasurement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TimeMeasurement.cpp.o
.PHONY : TimeMeasurement.cpp.o

TimeMeasurement.i: TimeMeasurement.cpp.i
.PHONY : TimeMeasurement.i

# target to preprocess a source file
TimeMeasurement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TimeMeasurement.cpp.i
.PHONY : TimeMeasurement.cpp.i

TimeMeasurement.s: TimeMeasurement.cpp.s
.PHONY : TimeMeasurement.s

# target to generate assembly for a file
TimeMeasurement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/TimeMeasurement.cpp.s
.PHONY : TimeMeasurement.cpp.s

geometry.o: geometry.cpp.o
.PHONY : geometry.o

# target to build an object file
geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/geometry.cpp.o
.PHONY : geometry.cpp.o

geometry.i: geometry.cpp.i
.PHONY : geometry.i

# target to preprocess a source file
geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/geometry.cpp.i
.PHONY : geometry.cpp.i

geometry.s: geometry.cpp.s
.PHONY : geometry.s

# target to generate assembly for a file
geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/geometry.cpp.s
.PHONY : geometry.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/detect.dir/build.make CMakeFiles/detect.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... detect"
	@echo "... CourtLineCandidateDetector.o"
	@echo "... CourtLineCandidateDetector.i"
	@echo "... CourtLineCandidateDetector.s"
	@echo "... CourtLinePixelDetector.o"
	@echo "... CourtLinePixelDetector.i"
	@echo "... CourtLinePixelDetector.s"
	@echo "... DebugHelpers.o"
	@echo "... DebugHelpers.i"
	@echo "... DebugHelpers.s"
	@echo "... GlobalParameters.o"
	@echo "... GlobalParameters.i"
	@echo "... GlobalParameters.s"
	@echo "... LicenseChecker.o"
	@echo "... LicenseChecker.i"
	@echo "... LicenseChecker.s"
	@echo "... Line.o"
	@echo "... Line.i"
	@echo "... Line.s"
	@echo "... TennisCourtFitter.o"
	@echo "... TennisCourtFitter.i"
	@echo "... TennisCourtFitter.s"
	@echo "... TennisCourtModel.o"
	@echo "... TennisCourtModel.i"
	@echo "... TennisCourtModel.s"
	@echo "... TimeMeasurement.o"
	@echo "... TimeMeasurement.i"
	@echo "... TimeMeasurement.s"
	@echo "... geometry.o"
	@echo "... geometry.i"
	@echo "... geometry.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

